# Generated by Django 5.2.5 on 2025-12-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
