# Generated by Django 5.2.5 on 2025-12-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
